---
- name: Reboot Windows Server
  hosts: all
  gather_facts: false
  tasks:
    - name: Reboot Windows
      win_reboot:
        reboot_timeout: 600  # Chờ tối đa 10 phút
        post_reboot_delay: 30  # Đợi 30s trước khi kiểm tra kết nối

    - name: Wait for Windows to be available
      wait_for_connection:
        timeout: 300  # Chờ tối đa 5 phút sau reboot
