---
- name: Reboot Windows Server
  hosts: all
  gather_facts: false
  tasks:
    - name: Reboot Windows machine
      win_reboot:
        reboot_timeout: 600  # Chờ tối đa 10 phút để Windows khởi động lại
