---
- name: Reboot Windows Server
  hosts: all
  gather_facts: false
  tasks:
    - name: Reboot the Windows machine
      win_reboot:
        reboot_timeout: 600
  - name: Wait for WinRM service to be available
    wait_for:
      port: 5985
      timeout: 300
