- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        #category_names: ['SecurityUpdates']
      register: result

    # output results
    - debug: var=result
    - name: Force Windows Update to refresh status
      win_command: UsoClient StartScan
    - name: Restart Windows Update service
      win_service:
        name: wuauserv
        state: restarted
